# Generated by Django 5.1.4 on 2026-01-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('kinescope_video_id', models.CharField(blank=True, max_length=100, verbose_name='Kinescope Video ID')),
                ('video_duration', models.PositiveIntegerField(default=0, help_text='Davomiyligi sekundlarda', verbose_name='Video davomiyligi')),
                ('notion_page_id', models.CharField(blank=True, max_length=100, verbose_name='Notion Page ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_from', models.DateTimeField(verbose_name='Ochilish vaqti')),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='groups.grouptype', verbose_name='Guruh turi')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['available_from'],
                'unique_together': {('lesson', 'group_type')},
            },
        ),
    ]
